"""Markdown ingestion — chunk, embed, persist to sqlite-vec."""

import logging
import re
from pathlib import Path

from pipeline.utils import build_doc_summary as _build_doc_summary

logger = logging.getLogger(__name__)


def _ingest_markdown(md_path: str, store_path: str, *,
                     doc_id: str = "doc_0", chunk_size: int = 1024) -> str:
    """Read a .md file, chunk, embed, and persist to sqlite-vec.

    This is the second step of a two-phase pipeline:
      1. `python -m pipeline md input.pdf`  →  generates .md
      2. `python -m pipeline ingest output/doc.md --store data/doc.db`

    Args:
        md_path: Path to the .md file generated by process_file_with_md().
        store_path: Path to sqlite-vec database (created if not exists).
        doc_id: Unique identifier for this document.
        chunk_size: Max characters per chunk.

    Returns:
        The store_path on success.

    Raises:
        FileNotFoundError: If md_path doesn't exist.
        RuntimeError: On embedding or storage failure.

    """
    md_file = Path(md_path)
    if not md_file.exists():
        _msg = f"Markdown file not found: {md_path}"
        raise FileNotFoundError(_msg)

    # Read the .md file
    md_content = md_file.read_text(encoding="utf-8")
    logger.info("Ingesting %s: %d chars", md_file.name, len(md_content))

    # Extract title from first `# Title`; tags from YAML front matter (if any)
    title = "Untitled Document"
    title_match = re.search(r"^#\s+(.+)$", md_content, re.MULTILINE)
    if title_match:
        title = title_match.group(1).strip()

    from pipeline.markdown_utils import parse_frontmatter
    frontmatter = parse_frontmatter(md_content)
    raw_tags = frontmatter.get("tags", [])
    if isinstance(raw_tags, str):
        raw_tags = [raw_tags]
    tags = [str(t) for t in raw_tags]

    # Chunk
    from chunkers import Chunker
    chunker = Chunker(chunk_size=chunk_size)
    all_chunks = chunker.chunk(md_content)
    logger.info("  → %d chunks from %s", len(all_chunks), md_file.name)

    # Embed + store
    from embedders import create_embedder
    from storage.sqlite_vec import SQLiteVecStore

    with create_embedder() as e:
        stored_chunks = e.store_chunks(all_chunks, doc_id=doc_id)

        summary_text = _build_doc_summary(title, tags, md_content)
        stored_doc = e.store_document(
            title=title,
            tags=tags,
            text_summary=summary_text,
            source_file=str(md_file.resolve()),
            total_chunks=len(stored_chunks),
        )

        with SQLiteVecStore(store_path) as db:
            db.upsert_chunks(stored_chunks, doc_id=doc_id)

            doc_embedding = stored_doc.get("embedding")
            db.upsert_document(
                title=title,
                tags=tags,
                text_summary=summary_text,
                source_file=str(md_file.resolve()),
                total_chunks=len(stored_chunks),
                embedding=doc_embedding,
            )

    logger.info("  → Persisted %d chunks + 1 doc to %s", len(stored_chunks), store_path)
    return store_path
